INSERT INTO `froms`(`region_state`, `country`) VALUES ('GT','GT'); /*1*/
INSERT INTO `froms`(`region_state`, `country`) VALUES ('NY','USA');/*2*/
INSERT INTO `froms`(`region_state`, `country`) VALUES ('FX','USA');/*3*/
INSERT INTO `froms`(`region_state`, `country`) VALUES ('AL','USA');/*4*/
INSERT INTO `froms`(`region_state`, `country`) VALUES ('PA','USA');/*5*/
INSERT INTO `froms`(`region_state`, `country`) VALUES ('CA','USA');/*6*/
INSERT INTO `froms`(`region_state`, `country`) VALUES ('CT','USA');/*7*/

INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1 MAPLE ST','NEW YORK HILLS','10080','2');

INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10 COURTNEY LN', 'BREWSTER', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('16 MAPLEWOOD DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('104 GROVE ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('106 SPRING ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('107 ORCHARD RD', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('12 BOLTIS ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('120 WOOD RIDGE RD', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('131 MAPLE AVE', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('14 TALLMAN LN', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('144 HONEY RD', 'POUND ROAD', '10576', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('15 HAMMOND RIDGE RD', 'BEDFORD CORNERS', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('18 HOLLOW RIDGE RD', 'BEDFORD CORNERS', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('16 GUARD HILL RD', 'BEDFORD CORNERS', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('160 E MAIN ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('165 E MAIN ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('17 HILLS SIDE AVE', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('170 GROVE ST', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('173 LEXINGTON AVE', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('18 PARK DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('19 EAST MAIN ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('190 BARBIT RD', 'BEDFORD HILLS', '10507', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1902 REGRET DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('20 CAMPENTER AVE', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('28 E HOLLOW RD', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('26 LITTLE PINE RD', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('20 SUNDERLAND LN', 'KATONAH', '10536', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('200 DIPLOMAT DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('223 STARR RIDGE', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('225 CANTITOE ST', 'KATONAH', '10536', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('228 SALMONS HOLLOW DR', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('23 RUTLAND ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('237 E MAIN ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('24 PINES LN', 'CHAPQUA', '10514', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('244 WEST ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('250 VESEY ST', 'NEW YORK HILLS', '10080', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('273 STARR RIDGE', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('28 BARKER ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('28 W 27TH ST', 'NEW YORK', '10009', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5 HERELD', 'NEW YORK', '10001', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3006 VICTORIA DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('32 FOX WOOD CIR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('328 LEXINGTON AVE', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('330 ARMOUNT RD', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3804 VICTORIA DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('39 ROME AVE', 'BEDFORD HILLS', '10507', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4 WORLD FINANCIAL CN', 'NEW YORK', '10080', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('435 LEXINGTON AVE', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5 LAKESIDE RD', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5 MILAN AVE', 'BEDFORD HILLS', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('50 BARKER ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('57 SPRING ST', 'MOUNTKISCO', '10549',2);




INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('59 FOX WOOD', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6 CYNTHIA ST', 'BEDFORD CORNERS', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('61 N GREELEY AVE', 'CHPPQUA', '10514', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7 W HOLLOW RD', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('70 BARKERT ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('72 BOLTIS ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('78 MAIN ST', 'BREWSTER', '10507', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('74 MAPLE AVE', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('75 TRIPP ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('83 OAK ST', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('85 CROTON AVE', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('88 LEXINGTON AVE', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('89 MARVIN AVE', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9 AVENUE A', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('90 GROVE ST', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('92 FOX WOOD CIR', 'MOUNTKISCO', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('966 AVENUE OT', 'NEW YORK', '10001', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('25 MAPLE ST', 'NEW YORK HILLS', '10080', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('61 E MAIN ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('77 GUARD HILL RD', 'BEDFORD CORNERS', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('65 GROVE ST', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('30 HONEY RD', 'POUND ROAD', '10576', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('200 BARBIT RD', 'BEDFORD HILLS', '10507', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('260 PINES LN', 'CHAPQUA', '10514', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('126 ROME AVE', 'BEDFORD HILLS', '10507', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('70 MILAN AVE', 'BEDFORD HILLS', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('40 DIPLOMAT DR', 'MOUNTKISCO', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('311 MAPPLE ST', 'NEW YORK HILLS', '10080', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('35 MAIN ST', 'BREWSTER', '10549', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('708 HURST BLVD', 'HURST', '70053', 3);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('824 SUDNEY ST', 'VALLEY', '36824', 4);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2124 JOHNSTON DR. APT 10', 'BETHLEHEM', '18020', 5);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('13357 BURBANK BLV APT 6', 'VANNVYS', '91401', 6);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('177 LEXINGTON AVE', 'MOUNTKISCO', '10544', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('992 ROUTE 22', 'BREWSTER', '10509', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('62 N HIGHLAND AVE', 'OSSINING', '10562', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('686 BRADWAY', 'KINGSTON', '12401', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('359 SOMERSET ST', 'NORTH PLAINFIELD (NJ)', '07060', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('28 S MAIN ST', 'SPRING VALLEY', '10977', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('282 N MAIN ST', 'FREEPORT', '11520', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('901 MAIN ST, 800', 'PEEKSKILL', '10566', 2);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('24 ELM ST', 'DANBURY', '06810', 7);





INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COMUNIDAD EL MITCH ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 21 COLONIA GRANDE ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LA LIBERTAD ZONA 0', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2AVE. CALLE C 1-11 ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('11AVE. 7-38 ZONA 1', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA CERRO DE CAL ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CASA 63, ACCESO B ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6TA. CALLE B 2-09 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10A. CALLE 6A.AVENIDA 2-95 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1RA. CALLE 1RA AVENIDA 1-22 ZONA 2', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA BRISAS 16-03 ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3A. AVENIDA 4-18 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4A. CALLE 7-09 ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CALLE SANTO TOMAS DE CASTILLA 5-95', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CARRETERA SAN LUIS JILOTEPEQUE ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO MODERNO CALLE B 11-97 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4A. CALLE 3-01 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('16 CALLE 7AVENIDA 7-79 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6A. AVENIDA .3RA CALLE FINAL ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 14 ALDEA PLAYITA ZONA 0.', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 18 CALLE IGLESIA MARGARITA ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6AVE. 3-00 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9 CALLE 8-10 ZONA 5', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLE SECTOR BLOQUERA ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA NAGUA ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('RUTA 2 2-15', 'CHIQUIMULA', '', 1);

INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA TASHAN ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9AVE. Y 14 CALLE ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6TA. CALLE 3-50 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 6 CASERIO LOS ARROZALES ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('AVENIDAD CEMENTERIO 14-03 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('RUTA 4 4-95 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5TA. CALLE 8-50 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CASERIO EL OBRAJE ZONA 0', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CALLE PALO GORDO ZONA 0', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7A. CALLE 5-31 COLONIA MONTSERRAL-ZONA 3', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6TA. CALLE PLAZA LAS CAMPANAS 5-14 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5TA. CALLE 6-74 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2A. AVENIDA 11-94 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTIFICACION VALLE REAL ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7AVE. 4-77 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2A. CALLE 7AVE. 2-37 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 10 ALDEA EL ZAPATAL ZONA 0', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. CALLE A 2-21 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9A. AVENIDA Y 4A. CALLE 9-77 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('18 CALLE 10-65 ZONA 11', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2DA. CALLE 31-25 ZONA 7', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10 CALLE 10-43 ZONA 4', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA EL PEDRERO ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5A. CALLE E 12-08 ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO LA REFORMA 2-05 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2A.AVENIDA 2-99 CALLE M ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA EL TESORO 6-38 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('AV SIMON BOLIVAR 5-90 A ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA CONACASTES ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA CRUZ VALLE ZONA 0', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('14 AVENIDA 3-25 ZONA 1', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA MOJANALES ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('20 CALLE Y 13 AVENIDA ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. CALLE MERCADO POPTUN ZONA 1', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 3 ALDEA POJOPAN ZONA 0', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5AVE. 5-55 ZONA 4', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA LOS CIMIENTOS ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8A. AVENIDA C 12-37 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('11 CALLE 1-74 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7TA. AVENIDA 5-45 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8AV. 2DA. CALLE E ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA LA CANDELARIA ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO NUEVO 1 3-85 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10A. AVENIDA B 11-36 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA TIMUSHAN ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('13 CALLE 4-54 ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA TORERA ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA EL MANACO ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA MOJANALES ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8A. CALLE 4-40 ZONA 2', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA SANTA ROSA ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9A. CALLE 1-01 ZONA 4', 'ESQUIPULAS', '', 1);

INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('KILOMETRO 173, RUTA 5', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA EL TESORO ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. CALLE 19-03 ZONA 3', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 15 BARRIO EL CEMENTERIO ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8AVE. COLONIA EL MIRADOR ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 12 COLONIA SAN FRANCISCO ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9AVE. 17 CALLE ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CALZADA ROOSEVELT 25-50 ZONA 7', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLE 6-90 COLONIA TENEDORES ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10A. CALLE 2-01 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8 AVENIDA VICENTE COZZA ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1RA. AVENIDA 10-86 ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('23 CALLE 1-05 ZONA 1', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA EL NANCE 12-26 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('19 CALLE 13-86 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2A. CALLE 8-69 ZONA 4', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 5 ALDEA EL SAUCE ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('16 CALLE Y 7AVE ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA EL ESTRECHO', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10A. CALLE 6-26 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6TA. CALLE 3-61 AVENIDA D ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2A. CALLE A 0-10 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO PUEBLO NUEVO', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 40 BARRIO EL CARRIZAL ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CASERIO LA ALAMBRADOS 0', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLE 13-10 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA CHANMAQUA ZONA 0', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 7 COLONIA EL BOSQUE ZONA 2', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10 C 3-25 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA LA JOYA ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('27 AV. 21-01 ZONA 16', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 2 COLONIA TULIO MANZO ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLLE M 12-05 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10AV. 4-25 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9A. AVENIDA 13-15 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA SANTA ANITA ZONA 0', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1A. CALLE B 5-20 ZONA 2', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTIFICACION SANTA BARBARA, ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 7 MANZANA C 1-21 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8AVE. EL VIAJERO 14-45 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLE LOTE 3 ALDEA CANDELARIA ZONA 1', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6TA AVENIDA A 5-97 ZONA 18', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6 AVENIDA 2-43 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10A. AVENIDA 5-38 ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2 CALLE 1-21 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. AVENIDA ZONA 2', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7TA.CALLE 12-33 ZONA 1', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA TIERRA COLORADA ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLE JARDINES DE LA ASUNCION 5-62', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA LAS ROSAS 2-02', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8AV. CALLE 6-48 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA VILLA ROSALES ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('8A. AVENIDA 6-64 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA EL RODEO ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO NUEVO 2-84 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3A. AVENIDA 10-46 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2AVE. CALLE LAS MARGARITAS ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. CALLE 19-09 ZONA 3', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CALLE NUEVO SAN JUAN 4-22 ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3RA. CALLE LOTE 3 ALDEA CANDELARIA ZONA 1', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10AV. 3-73 ZONA 4', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO LA LONA', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7A. CALLE A 3-31 ZONA 2', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('10A. CALLE 1-12 ZONA 4', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA NUEVA CONCEPCION', 'CONCEPCION LAS MINAS', '', 1);



INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CALLEJON LOS MORALES ZONA 5', 'CHIQUIMULA', '', 1);

INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. CALLE 23-80 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3A. AVENIDA 8-00 ZONA 1', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5AVE. 10-04 SAN BENITO', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2DA. CALLE 5-98 ZONA 1 BARRIO SANTA MONICA', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA TOBAR ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. AVENIDA 1-17 ZONA 1', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA SAN MANUEL 7-94 ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('2DA. CALLE LA COLINA 11-02 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9AVE. 19 CALLE ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1RA. CALLE 2-22 ALDEA EL LUTE ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA COMOLOTE ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('0 CALLE 0-84 ZONA 8', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. CALLE 3-15 BARRIO EL CALVARIO ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 3 ALDEA EL RINCON ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6A. CALLE 3-64 ZONA 2', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7TA. CALLE C 14-38 ZONA 3 DE MIXCO', 'GUATEMALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('RUTA 3 3-65 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO EL SOLAPADO', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('AV. LAS AMERICAS 704 ZONA 3', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA LAGUNA ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO EL CENTRO 6-96 ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('16 AVE. 4-70 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('CALLE 15 DE SEPTIEMBRE 4-93 ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA LOS LIMONES ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('COLONIA ELLIMONAR', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('3AV. 1-02 KM 206 LA ESPERANZA', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO RUFINO 8-06 ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('1RA. CALLE 3-84 ZONA 2', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6A. CALLE 5-49 ZONA 1', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA LAS PEÑAS ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('D-179 COLONIA FALLABAN MELCHOR', 'PETEN POPTUN', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('11 AVE. 30-74 ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('FINCA EL TULE ZONA 0', 'SAN JOSE LA ARADA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA EL MARISCO ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA EL RICO ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('4TA. C 12-49 ZONA 1', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('BARRIO MILLA 37-0 ZONA 0', 'MORALES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA TONTOL ZONA 0', 'LOS AMATES', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7TA.AVENIDA AZUL 2-42 ZONA 1', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('25 AVE. 8-25 ZONA 3', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('6TA. CALLE 12-22 ZONA 1', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('9 CALLE FINAL ZONA 0', 'PUERTO BARRIOS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA RODE ESPINO ZONA 0', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('ALDEA ANGUIATU ZONA 0', 'CONCEPCION LAS MINAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('11 CALLE 8-11 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('5TA. CALLE 12-46 ZONA 1', 'QUETZALTEPEQUE', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('12 AV. 3-01 ZONA 1', 'CHIQUIMULA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('LOTE 5 CALLE PRINCIPAL ZONA 0', 'ESQUIPULAS', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('7A. AVENIDA 7-82 ZONA 0', 'IPALA', '', 1);
INSERT INTO `address`(`address`, `city`, `postal_code`, `id_from`) VALUES ('20 CALLE 7-62 ZONA 7', 'GUATEMALA', '', 1);

